# Generated by Django 3.1.1 on 2021-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20210529_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (2, 'Academic lyceum diploma'), (0, 'Others'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='error_fill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
