# Generated by Django 3.1.1 on 2021-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_auto_20210529_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(0, 'Others'), (1, 'Certificate'), (3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='error_fill',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
