# Generated by Django 3.1.1 on 2021-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20210529_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rekvizit',
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(0, 'Others'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma'), (1, 'Certificate')]),
        ),
    ]
