# Generated by Django 3.1.1 on 2021-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_auto_20210529_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Curricula',
        ),
        migrations.RemoveField(
            model_name='elibraryfiles',
            name='elibrary',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.RemoveField(
            model_name='library',
            name='category',
        ),
        migrations.RemoveField(
            model_name='libraryfiles',
            name='library',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='thesisfiles',
            name='thesis',
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (0, 'Others'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
        migrations.DeleteModel(
            name='Elibrary',
        ),
        migrations.DeleteModel(
            name='ElibraryFiles',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='LibraryCategory',
        ),
        migrations.DeleteModel(
            name='LibraryFiles',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
        migrations.DeleteModel(
            name='ThesisFiles',
        ),
    ]
