# Generated by Django 3.1.1 on 2021-05-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20210529_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(3, 'Secondary specialized and vocational College diploma'), (0, 'Others'), (1, 'Certificate'), (2, 'Academic lyceum diploma')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizenship', to='admin_panel.nationality'),
        ),
    ]
