# Generated by Django 3.1.1 on 2021-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_auto_20210529_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_sr', models.CharField(max_length=255, null=True)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'top_link',
            },
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma'), (0, 'Others'), (1, 'Certificate')]),
        ),
    ]
