# Generated by Django 3.1.1 on 2021-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_auto_20210529_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(0, 'Others'), (3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma'), (1, 'Certificate')]),
        ),
    ]
