# Generated by Django 3.1.1 on 2021-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_auto_20210529_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagesetting',
            name='location',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(3, 'Secondary specialized and vocational College diploma'), (0, 'Others'), (2, 'Academic lyceum diploma'), (1, 'Certificate')]),
        ),
    ]
