# Generated by Django 3.1.1 on 2021-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_auto_20210529_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(2, 'Academic lyceum diploma'), (1, 'Certificate'), (3, 'Secondary specialized and vocational College diploma'), (0, 'Others')]),
        ),
        migrations.AlterField(
            model_name='mainpagesetting',
            name='location',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
