# Generated by Django 3.1.1 on 2021-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20210529_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectorcongratulation',
            name='date',
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma'), (1, 'Certificate'), (0, 'Others')]),
        ),
    ]
