# Generated by Django 3.1.1 on 2021-05-29 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_auto_20210529_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(2, 'Academic lyceum diploma'), (1, 'Certificate'), (3, 'Secondary specialized and vocational College diploma'), (0, 'Others')]),
        ),
        migrations.AlterField(
            model_name='rectorcongratulation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
