# Generated by Django 3.1.1 on 2021-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_auto_20210601_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionpage',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='content_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionpage',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma'), (1, 'Certificate'), (0, 'Others')]),
        ),
    ]
