# Generated by Django 3.1.1 on 2021-06-03 12:48

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_auto_20210601_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='Salom salom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (2, 'Academic lyceum diploma'), (0, 'Others'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.FileField(upload_to='facultylogo'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=81, size=[280, 372], upload_to='news'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=81, size=[280, 372], upload_to='photo_gallery_thumbnails'),
        ),
        migrations.AlterField(
            model_name='sciencenews',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=81, size=[280, 372], upload_to='news'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=81, size=[280, 372], upload_to='news'),
        ),
        migrations.AlterField(
            model_name='vebinar',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=81, size=[280, 372], upload_to='video_gallery_thumbnails'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=81, size=[280, 372], upload_to='video_gallery_thumbnails'),
        ),
    ]
