# Generated by Django 3.1.1 on 2021-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_auto_20210603_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (0, 'Others'), (3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma')]),
        ),
    ]
