# Generated by Django 3.1.1 on 2021-06-07 06:29

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_auto_20210603_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=81, size=[1200, 675], upload_to='static_gallery'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (0, 'Others'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
    ]
