# Generated by Django 3.1.1 on 2021-06-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_auto_20210607_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='rector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (2, 'Academic lyceum diploma'), (0, 'Others'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
    ]
