# Generated by Django 3.1.1 on 2021-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_auto_20210607_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (0, 'Others'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
