# Generated by Django 3.1.1 on 2021-06-07 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_auto_20210607_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-rector', 'order', '-leader', '-main']},
        ),
        migrations.RemoveField(
            model_name='grant',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='staticpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(3, 'Secondary specialized and vocational College diploma'), (1, 'Certificate'), (0, 'Others'), (2, 'Academic lyceum diploma')]),
        ),
        migrations.DeleteModel(
            name='GrantHashtag',
        ),
    ]
