# Generated by Django 3.1.1 on 2021-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_auto_20210608_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(2, 'Academic lyceum diploma'), (0, 'Others'), (3, 'Secondary specialized and vocational College diploma'), (1, 'Certificate')]),
        ),
    ]
