# Generated by Django 3.1.1 on 2021-06-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_auto_20210608_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(2, 'Academic lyceum diploma'), (0, 'Others'), (1, 'Certificate'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='admin_panel.country'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_person', to='admin_panel.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.nationality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='place_of_birth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.country'),
            preserve_default=False,
        ),
    ]
