# Generated by Django 3.1.1 on 2021-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_auto_20210608_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalrelation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='service',
            name='white_icon',
            field=models.FileField(blank=True, null=True, upload_to='icon'),
        ),
    ]
