# Generated by Django 3.1.1 on 2021-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_auto_20210609_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(0, 'Others'), (1, 'Certificate'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
    ]
