# Generated by Django 3.1.1 on 2021-06-11 18:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_auto_20210610_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', models.FileField(upload_to='static_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalPartnerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, null=True, quality=81, size=[1200, 675], upload_to='static_gallery')),
            ],
        ),
        migrations.AlterModelOptions(
            name='conferencesubject',
            options={'ordering': ['-start_date', 'id', 'conference__id', 'conference__pk']},
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma'), (0, 'Others')]),
        ),
    ]
