# Generated by Django 3.1.1 on 2021-06-11 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_auto_20210611_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalpartnerpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (0, 'Others'), (3, 'Secondary specialized and vocational College diploma'), (2, 'Academic lyceum diploma')]),
        ),
    ]
