# Generated by Django 3.1.1 on 2021-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_auto_20210612_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(0, 'Others'), (2, 'Academic lyceum diploma'), (1, 'Certificate'), (3, 'Secondary specialized and vocational College diploma')]),
        ),
    ]
