# Generated by Django 3.1.1 on 2021-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0049_auto_20210612_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma'), (0, 'Others')]),
        ),
    ]
