# Generated by Django 3.1.1 on 2021-06-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0050_auto_20210612_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectorcongratulation',
            name='rector_fullname_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rectorcongratulation',
            name='rector_fullname_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rectorcongratulation',
            name='rector_fullname_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rectorcongratulation',
            name='rector_fullname_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
