# Generated by Django 3.1.1 on 2021-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0051_auto_20210614_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
