# Generated by Django 3.1.1 on 2021-06-26 04:56

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_auto_20210621_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_sr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=81, size=[1920, 1080], upload_to='', verbose_name=[279, 287])),
                ('button_title', models.CharField(max_length=64)),
                ('button_title_uz', models.CharField(max_length=64, null=True)),
                ('button_title_sr', models.CharField(max_length=64, null=True)),
                ('button_title_en', models.CharField(max_length=64, null=True)),
                ('button_title_ru', models.CharField(max_length=64, null=True)),
                ('button_link', models.URLField()),
            ],
        ),
    ]
