# Generated by Django 3.1.1 on 2021-06-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0054_sidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='sidebar',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
