# Generated by Django 3.1.1 on 2021-06-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0055_auto_20210626_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebar',
            old_name='button_link',
            new_name='link',
        ),
    ]
