# Generated by Django 3.1.1 on 2021-06-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0057_unversityfile_ustav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ustav',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='ustav',
            old_name='description_en',
            new_name='short_description_en',
        ),
        migrations.RenameField(
            model_name='ustav',
            old_name='description_ru',
            new_name='short_description_ru',
        ),
        migrations.RenameField(
            model_name='ustav',
            old_name='description_sr',
            new_name='short_description_sr',
        ),
        migrations.RenameField(
            model_name='ustav',
            old_name='description_uz',
            new_name='short_description_uz',
        ),
    ]
