# Generated by Django 3.1.1 on 2021-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0058_auto_20210626_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutministry',
            name='file',
            field=models.FileField(null=True, upload_to='aboutministry/'),
        ),
        migrations.AlterField(
            model_name='unversityfile',
            name='file',
            field=models.FileField(null=True, upload_to='unversitet'),
        ),
    ]
