# Generated by Django 3.1.1 on 2021-06-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0059_auto_20210626_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videogallery',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
