# Generated by Django 3.1.1 on 2021-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0061_videogallery_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='vebinar',
            name='author_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vebinar',
            name='author_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vebinar',
            name='author_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vebinar',
            name='author_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
