# Generated by Django 3.1.1 on 2021-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0062_auto_20210703_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousgraduate',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='famousgraduate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='famousgraduate',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='famousgraduate',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
