# Generated by Django 3.1.1 on 2021-07-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0064_mainpagesetting_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='link_sr',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='link_uz',
        ),
    ]
