# Generated by Django 3.1.1 on 2021-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0065_auto_20210709_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='main_page',
            field=models.BooleanField(default=True),
        ),
    ]
