# Generated by Django 3.1.1 on 2021-07-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0067_menu_only_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='only_footer',
        ),
    ]
