# Generated by Django 3.1.1 on 2021-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0068_remove_menu_only_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='only_footer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
