# Generated by Django 3.1.1 on 2021-07-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0069_auto_20210724_1709'),
        ('admin_panel', '0069_menu_only_footer'),
    ]

    operations = [
    ]
