# Generated by Django 3.1.1 on 2021-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0070_merge_20210724_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'ordering': ['-id'], 'verbose_name': 'Hamkor', 'verbose_name_plural': 'Hamkorlar'},
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='rasulov@sa.saa', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='account_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='bank',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='fax',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='inn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='mfo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='okonx',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mainpagesetting',
            name='shxr',
            field=models.CharField(default='', max_length=255),
        ),
    ]
