# Generated by Django 3.1.1 on 2021-07-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0071_auto_20210726_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrantpage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='entrantpage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Jarayonda'), (1, "Ko'rildi"), (2, 'Rad etildi')], default=0),
        ),
    ]
