# Generated by Django 3.1.1 on 2021-08-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0072_auto_20210726_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecatalog',
            options={'ordering': ['-created_at']},
        ),
    ]
