# Generated by Django 3.1.1 on 2021-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0075_auto_20210819_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyfield',
            name='toggle',
            field=models.BooleanField(default=False, verbose_name='Is required?'),
        ),
        migrations.AlterField(
            model_name='vacancyfield',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'email'), (3, 'textarea'), (4, 'date'), (5, 'checkbox'), (6, 'radio'), (7, 'radio + input'), (8, 'select'), (9, 'select + input'), (10, 'file'), (11, 'file + input')], verbose_name='Field turi'),
        ),
        migrations.AlterField(
            model_name='vacantfieldvalue',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'email'), (3, 'textarea'), (4, 'date'), (5, 'checkbox'), (6, 'radio'), (7, 'radio + input'), (8, 'select'), (9, 'select + input'), (10, 'file'), (11, 'file + input')], verbose_name='Field turi'),
        ),
    ]
