# Generated by Django 3.1.1 on 2021-08-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0076_auto_20210820_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantfieldvalue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.vacantfieldvalue'),
        ),
        migrations.AlterField(
            model_name='vacancyfield',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'email'), (3, 'textarea'), (4, 'date'), (5, 'select'), (6, 'file'), (7, 'radio'), (8, 'checkbox'), (9, 'checkbox + textarea'), (10, 'checkbox + file')], verbose_name='Field turi'),
        ),
        migrations.AlterField(
            model_name='vacantfieldvalue',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'email'), (3, 'textarea'), (4, 'date'), (5, 'select'), (6, 'file'), (7, 'radio'), (8, 'checkbox'), (9, 'checkbox + textarea'), (10, 'checkbox + file')], verbose_name='Field turi'),
        ),
    ]
