# Generated by Django 3.1.1 on 2021-12-23 10:11

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0079_auto_20211013_1838'),
    ]

    operations = [

        migrations.AlterField(
            model_name='report',
            name='quarter',
            field=models.SmallIntegerField(choices=[(1, '1-chorak'), (2, '2-chorak'), (3, '3-chorak'), (4, '4-chorak'), (5, 'yillik'), (6, 'yarim yillik'), (7, '9 oylik')], default=1),
        ),

    ]
