# Generated by Django 3.1.1 on 2022-05-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0081_auto_20220215_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='content_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='content_sr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='content_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='admin_panel.coursecatalog'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='credits',
            field=models.PositiveSmallIntegerField(blank=True, default=240, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='languages',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='qualification',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='qualification_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='qualification_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='qualification_sr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='qualification_uz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='shifr',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='study_plan',
            field=models.FileField(blank=True, null=True, upload_to='study_plan'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='study_year',
            field=models.PositiveSmallIntegerField(blank=True, default=4, null=True),
        ),
    ]
