# Generated by Django 3.1.1 on 2022-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0082_auto_20220517_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='shifr',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
