# Generated by Django 3.1.1 on 2022-06-21 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0083_auto_20220614_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diploma', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'gif', 'jpg', 'pdf', 'png', 'jpeg', 'zip'])], verbose_name='Copy of the higher education document'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='passport_copy',
            field=models.FileField(upload_to='passports', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
