# Generated by Django 3.1.1 on 2022-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0084_auto_20220621_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
