# Generated by Django 3.1.1 on 2022-07-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0085_auto_20220714_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizenship', to='admin_panel.country'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_person', to='admin_panel.country'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.nationality'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.country'),
        ),
        migrations.AlterField(
            model_name='vacant',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.nationality', verbose_name='Millatingiz'),
        ),
    ]
