# Generated by Django 3.1.1 on 2022-07-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0086_auto_20220714_1735'),
        ('admin_panel', '0085_auto_20220714_1606'),
    ]

    operations = [
    ]
