# Generated by Django 3.1.1 on 2022-07-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0087_merge_20220718_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nationality',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
