# Generated by Django 3.1.1 on 2022-10-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0088_auto_20220718_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['title']},
        ),
    ]
