# Generated by Django 3.1.1 on 2022-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0089_auto_20221029_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='Application')),
                ('phone_number', models.CharField(max_length=9)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
    ]
