# Generated by Django 3.1.1 on 2022-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0090_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
