# Generated by Django 3.1.1 on 2022-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0092_auto_20221031_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_sr', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_sr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('reception_time', models.CharField(max_length=255)),
                ('reception_time_uz', models.CharField(max_length=255, null=True)),
                ('reception_time_sr', models.CharField(max_length=255, null=True)),
                ('reception_time_en', models.CharField(max_length=255, null=True)),
                ('reception_time_ru', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'science_center',
                'ordering': ['-created_at'],
            },
        ),
    ]
