# Generated by Django 3.1.1 on 2022-11-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0093_sciencecenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
