# Generated by Django 3.1.1 on 2022-11-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0094_newscategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ('order',)},
        ),
    ]
