# Generated by Django 3.1.1 on 2022-11-08 15:44

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0095_auto_20221104_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1200, 675], upload_to='news')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.news')),
            ],
        ),
    ]
