# Generated by Django 3.1.1 on 2022-11-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0098_auto_20221108_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_panel.news'),
        ),
    ]
