# Generated by Django 3.1.1 on 2022-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0100_scientificjournal_scientificjournaldesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificjournal',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
