# Generated by Django 3.1.1 on 2022-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0102_scientificjournal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificjournal',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='scientificjournal',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='scientificjournal',
            name='description_sr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='scientificjournal',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
