# Generated by Django 3.1.1 on 2022-11-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0103_auto_20221111_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalconferencepage',
            options={'ordering': ['-updated_at']},
        ),
    ]
