# Generated by Django 3.1.1 on 2022-11-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0106_auto_20221130_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-created_at',)},
        ),
    ]
