# Generated by Django 3.1.1 on 2022-11-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0107_auto_20221130_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='work_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_history_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_history_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_history_sr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_history_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
