# Generated by Django 3.1.1 on 2022-12-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0110_auto_20221206_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='admin_panel.department'),
        ),
    ]
