# Generated by Django 3.1.1 on 2022-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0113_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='content_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='title_en',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='title_ru',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='title_sr',
            field=models.CharField(max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='title_uz',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
