# Generated by Django 3.1.1 on 2022-12-14 11:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0118_auto_20221210_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to='staff'),
        ),
    ]
