# Generated by Django 3.1.1 on 2022-12-22 11:53

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0119_auto_20221214_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1200, 675], upload_to='external_sections')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'external_section',
                'ordering': ['-updated_at'],
            },
        ),
    ]
