# Generated by Django 3.1.1 on 2023-01-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0122_direction_education_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='education_type',
            field=models.CharField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('online', 'Masofaviy'), ('kechgi', 'Kechgi')], default='kunduzgi', max_length=32),
        ),
    ]
