# Generated by Django 3.1.1 on 2023-01-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0123_auto_20230106_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplink',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='admin_panel.toplink'),
        ),
    ]
