# Generated by Django 3.1.1 on 2023-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0124_toplink_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
