# Generated by Django 3.1.1 on 2023-01-31 19:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0125_auto_20230121_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='education_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('kunduzgi', 'Kunduzgi'), ('sirtqi', 'Sirtqi'), ('online', 'Masofaviy'), ('kechgi', 'Kechgi')], default='kunduzgi', max_length=32),
        ),
    ]
