# Generated by Django 3.1.1 on 2023-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0126_auto_20230131_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
