# Generated by Django 3.1.1 on 2023-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0127_studyprogram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
