# Generated by Django 3.1.1 on 2023-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0128_department_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.SmallIntegerField(choices=[(1, 'Markaz'), (2, "Bo'lim"), (3, 'Departament')]),
        ),
    ]
