# Generated by Django 3.1.1 on 2023-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0130_conferenceapplication_conferencetags_pendingconference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingconference',
            name='time',
        ),
        migrations.AddField(
            model_name='pendingconference',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='pendingconference',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='pendingconference',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='pendingconference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
    ]
