# Generated by Django 3.1.1 on 2023-05-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0131_auto_20230516_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingconference',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='conference', verbose_name='Icon'),
        ),
    ]
