# Generated by Django 3.1.1 on 2023-05-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0132_pendingconference_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
