# Generated by Django 3.1.1 on 2023-05-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0133_conferenceapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalFacultyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('video_url', models.URLField(verbose_name='Video URL')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalFacultyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('passport_front', models.ImageField(upload_to='international_faculty')),
                ('passport_back', models.ImageField(upload_to='international_faculty')),
                ('image_3_4', models.ImageField(upload_to='international_faculty')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('phone_number1', models.CharField(max_length=30, verbose_name='Phone number 1')),
                ('phone_number2', models.CharField(max_length=30, verbose_name='Phone number 2')),
                ('school_number', models.CharField(max_length=200, verbose_name='School number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coursecatalog', verbose_name='Category')),
            ],
        ),
    ]
