# Generated by Django 3.1.1 on 2023-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0134_internationalfacultyapplication_internationalfacultypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalfacultypage',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='content_sr',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='title_sr',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='internationalfacultypage',
            name='title_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='internationalfacultyapplication',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number 2'),
        ),
    ]
