# Generated by Django 3.1.1 on 2023-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0135_auto_20230518_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalfacultyapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
