# Generated by Django 3.1.1 on 2023-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0136_internationalfacultyapplication_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalfacultyapplication',
            name='is_form_invalid',
            field=models.BooleanField(default=False, verbose_name='Is form invalid'),
        ),
        migrations.AddField(
            model_name='internationalfacultyapplication',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Is reviewed'),
        ),
    ]
