# Generated by Django 3.1.1 on 2023-05-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0137_auto_20230518_1625'),
        ('admin_panel', '0134_auto_20230518_1123'),
    ]

    operations = [
    ]
