# Generated by Django 3.1.1 on 2023-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0138_merge_20230518_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagesetting',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
