# Generated by Django 3.1.1 on 2023-08-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0139_mainpagesetting_linkedin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalImage',
        ),
    ]
