# Generated by Django 3.2.1 on 2023-10-07 15:34

import admin_panel.model.courses
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0140_delete_externalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=admin_panel.model.courses.gen_file_name)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_requirements', to='admin_panel.direction')),
            ],
            options={
                'db_table': 'qualification_requirement',
            },
        ),
    ]
