# Generated by Django 3.2.1 on 2023-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0143_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='news', to='admin_panel.Objective'),
        ),
    ]
