# Generated by Django 3.2.1 on 2023-11-09 18:54

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0146_auto_20231109_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMissionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Our Mission Item',
                'verbose_name_plural': 'Our Mission Items',
            },
        ),
        migrations.AddField(
            model_name='ourmission',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1200, 675], upload_to='our_mission'),
        ),
        migrations.AddField(
            model_name='ourmission',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_item', to='admin_panel.ourmissionitem'),
        ),
    ]
