# Generated by Django 3.2.1 on 2023-11-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0148_auto_20231109_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourmission',
            name='item',
        ),
        migrations.AddField(
            model_name='ourmissionitem',
            name='our_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_item', to='admin_panel.ourmission'),
        ),
    ]
