# Generated by Django 3.2.1 on 2023-11-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0149_auto_20231109_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourmission',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is Main'),
        ),
    ]
