# Generated by Django 3.2.1 on 2023-11-10 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0150_ourmission_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='blue_icon',
            field=models.FileField(null=True, upload_to='statistic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Blue icon'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.FileField(null=True, upload_to='statistic', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='White Icon'),
        ),
    ]
