# Generated by Django 3.2.1 on 2023-11-10 16:35

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0151_auto_20231110_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
            },
        ),
        migrations.AddField(
            model_name='statisticitem',
            name='blue_image',
            field=models.FileField(null=True, upload_to='statistic'),
        ),
        migrations.CreateModel(
            name='HistoryYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, null=True, verbose_name='Year')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_year', to='admin_panel.history')),
            ],
            options={
                'verbose_name': 'History Year',
                'verbose_name_plural': 'History Years',
            },
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1200, 675], upload_to='history')),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_image', to='admin_panel.history')),
            ],
            options={
                'verbose_name': 'History Image',
                'verbose_name_plural': 'History Images',
            },
        ),
    ]
