# Generated by Django 3.2.1 on 2023-11-10 18:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0153_auto_20231110_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, scale=None, size=[800, 800], upload_to='foreign_student')),
                ('youtube_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foreign Student',
                'verbose_name_plural': 'Foreign Students',
                'db_table': 'foreign_student',
            },
        ),
    ]
