# Generated by Django 3.2.1 on 2023-11-21 14:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0154_foreignstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='country',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='extra_phone_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='passport_given_data',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='passport_issued_data',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='rel_email',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='rel_phone_number',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='relation',
        ),
        migrations.AddField(
            model_name='admission',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_user', to='admin_panel.customuser'),
        ),
        migrations.AddField(
            model_name='rectorcongratulation',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rectorcongratulation',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rectorcongratulation',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('accepted', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('in_moderation', 'Ko`rib chiqilmoqda')], default='in_moderation', max_length=25),
        ),
    ]
