# Generated by Django 3.2.1 on 2023-11-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0157_auto_20231121_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='email',
        ),
    ]
