# Generated by Django 3.2.1 on 2023-11-22 16:53

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0160_admission_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCooperationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_sr', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalCooperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_sr', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_uz', models.TextField(null=True, verbose_name='Content')),
                ('content_sr', models.TextField(null=True, verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='international_cooperation')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.internationalcooperationcategory', verbose_name='Category')),
            ],
        ),
    ]
