# Generated by Django 3.2.1 on 2023-11-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0161_internationalcooperation_internationalcooperationcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ranking')),
                ('reputation_ranking', models.FloatField(verbose_name='Reputation ranking')),
                ('academic_reputation_ranking', models.FloatField(verbose_name='Academic reputation ranking')),
                ('employer_reputation_ranking', models.FloatField(verbose_name='Employer reputation ranking')),
                ('reputation_assessment', models.FloatField(verbose_name='Reputation assestment')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
            },
        ),
    ]
