# Generated by Django 3.2.1 on 2023-11-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0163_jointprograms'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='why_tsue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='why_tsue_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='why_tsue_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='why_tsue_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='why_tsue_uz',
            field=models.TextField(null=True),
        ),
    ]
