# Generated by Django 3.2.1 on 2023-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0165_auto_20231123_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Order'),
        ),
    ]
