# Generated by Django 3.2.1 on 2023-11-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0166_history_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_uz', models.TextField(null=True)),
                ('content_sr', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('order', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Statistic Content Item',
                'verbose_name_plural': 'Statistic Content Items',
                'db_table': 'statistic_content_item',
                'ordering': ('order',),
            },
        ),
    ]
