# Generated by Django 3.2.1 on 2023-11-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0167_statisticcontentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admin_panel.direction'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admin_panel.coursecatalog'),
        ),
    ]
