# Generated by Django 3.2.1 on 2023-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0168_auto_20231127_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='language_qualifications',
            field=models.SmallIntegerField(choices=[(0, 'TOEFL'), (1, 'CEFR'), (2, 'IELTS'), (3, 'No Score')]),
        ),
    ]
