# Generated by Django 3.2.1 on 2023-11-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0169_alter_admission_language_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='certificate',
            field=models.SmallIntegerField(choices=[(1, 'Certificate'), (2, 'Academic lyceum diploma'), (3, 'Secondary specialized and vocational College diploma'), (0, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='document_series_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='education_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='have_higher_education',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='language_qualifications',
            field=models.SmallIntegerField(choices=[(0, 'TOEFL'), (1, 'CEFR'), (2, 'IELTS'), (3, 'No Score')], null=True),
        ),
    ]
