# Generated by Django 3.2.1 on 2023-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0170_auto_20231128_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
