# Generated by Django 3.2.1 on 2024-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0171_auto_20231128_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
