# Generated by Django 3.2.1 on 2024-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0175_faqquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='content_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faqquestion',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
