# Generated by Django 3.2.1 on 2024-05-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0178_studentactivities_studentactivitycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_sr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalendarFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='academic_calendar')),
                ('academic_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admin_panel.academiccalendar')),
            ],
        ),
    ]
