# Generated by Django 3.2.1 on 2024-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0180_auto_20240503_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Name'),
        ),
    ]
