# Generated by Django 3.2.1 on 2024-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0181_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bio_sr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bio_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
