# Generated by Django 3.2.1 on 2024-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0182_auto_20240504_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_sr', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='student_video')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='student_video')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
