# Generated by Django 3.2.1 on 2024-05-06 16:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0183_studentvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivities',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='content_sr',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentactivities',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='StudentActivityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('content_uz', ckeditor.fields.RichTextField(null=True)),
                ('content_sr', ckeditor.fields.RichTextField(null=True)),
                ('content_en', ckeditor.fields.RichTextField(null=True)),
                ('content_ru', ckeditor.fields.RichTextField(null=True)),
                ('student_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='admin_panel.studentactivities')),
            ],
        ),
    ]
