# Generated by Django 3.2.1 on 2024-05-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0184_auto_20240506_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivitycontent',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentactivitycontent',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentactivitycontent',
            name='title_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentactivitycontent',
            name='title_sr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='studentactivitycontent',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='StudentActivityContentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, null=True)),
                ('tag_uz', models.CharField(max_length=128, null=True)),
                ('tag_sr', models.CharField(max_length=128, null=True)),
                ('tag_en', models.CharField(max_length=128, null=True)),
                ('tag_ru', models.CharField(max_length=128, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='admin_panel.studentactivitycontent')),
            ],
        ),
    ]
