# Generated by Django 3.2.1 on 2024-05-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0185_auto_20240506_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivities',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
