# Generated by Django 3.2.1 on 2024-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0189_auto_20240513_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='news_gallery/'),
        ),
    ]
