# Generated by Django 3.1.1 on 2021-10-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20210826_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.job', verbose_name='Vakansiya'),
        ),
    ]
