# Generated by Django 3.1.1 on 2022-07-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_vacant_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacant',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.nationality', verbose_name='Millatingiz'),
        ),
    ]
