# Generated by Django 3.2.11 on 2023-05-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20230529_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacant',
            name='passport_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_file', to='hr.vacantfilefield', verbose_name='Pasportingiz'),
        ),
        migrations.AddField(
            model_name='vacantfieldvalue',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlang‘ich sanasi'),
        ),
        migrations.AddField(
            model_name='vacantfieldvalue',
            name='from_to',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='vacancyfield',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'email'), (3, 'textarea'), (4, 'date'), (5, 'select'), (6, 'file'), (7, 'radio'), (8, 'checkbox'), (9, 'checkbox + textarea'), (10, 'checkbox + file'), (11, 'Ish tajribasi')], verbose_name='Field turi'),
        ),
        migrations.AlterField(
            model_name='vacancyfield',
            name='step',
            field=models.SmallIntegerField(choices=[(2, "Ta'lim"), (3, 'Ilmiy'), (4, 'Mahorat'), (5, 'Mehnat faoliyati')], verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='vacantfieldvalue',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'email'), (3, 'textarea'), (4, 'date'), (5, 'select'), (6, 'file'), (7, 'radio'), (8, 'checkbox'), (9, 'checkbox + textarea'), (10, 'checkbox + file'), (11, 'Ish tajribasi')], verbose_name='Field turi'),
        ),
        migrations.AlterField(
            model_name='vacantfieldvalue',
            name='step',
            field=models.SmallIntegerField(choices=[(2, "Ta'lim"), (3, 'Ilmiy'), (4, 'Mahorat'), (5, 'Mehnat faoliyati')], verbose_name='Step'),
        ),
    ]
