# Generated by Django 3.1.1 on 2023-08-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselessonresource',
            options={'verbose_name': 'Course lesson resource', 'verbose_name_plural': 'Course lesson resources'},
        ),
        migrations.AlterField(
            model_name='coursesyllabustextsection',
            name='type',
            field=models.CharField(choices=[('1_science_description', '1. Science description'), ('2_purpose_of_science', '2. The Purpose of science'), ('3_results_of_education', '3. Results of Education'), ('4_teaching_methods', '4. Teaching methods'), ('5_assessment_methods', '5. Assessment of Student Knowledge'), ('6_academic_requirements', '6. Academic requirements'), ('7_independent_study', '7. Independent education and Independent work')], max_length=255, verbose_name='Type'),
        ),
    ]
