# Generated by Django 3.1.1 on 2023-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_auto_20230821_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
