# Generated by Django 3.1.1 on 2023-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_syllabus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.IntegerField(verbose_name='list order'),
        ),
    ]
