# Generated by Django 3.1.1 on 2023-08-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_auto_20230821_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselessonresource',
            name='course_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_resource', to='syllabus.courselesson', verbose_name='Course lesson'),
        ),
        migrations.AlterField(
            model_name='courselessonresource',
            name='course_syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_resource', to='syllabus.coursesyllabus', verbose_name='Course syllabus'),
        ),
    ]
