# Generated by Django 3.1.1 on 2023-08-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_auto_20230821_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselessonresource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
