# Generated by Django 3.1.1 on 2023-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_courselessonresource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselessonresource',
            name='order',
            field=models.IntegerField(verbose_name='List order'),
        ),
    ]
