# Generated by Django 3.2.1 on 2023-08-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_auto_20230821_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courselessonhour',
            unique_together={('type', 'lesson')},
        ),
    ]
