# Generated by Django 3.2.1 on 2023-08-25 17:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_alter_courselessonhour_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name': 'Department Syllabus', 'verbose_name_plural': 'Department Syllabuses'},
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_assessment', models.CharField(max_length=3000)),
                ('max_ball', models.IntegerField()),
                ('task_to_be_completed', ckeditor_uploader.fields.RichTextUploadingField()),
                ('task_completion_time', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('course_syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='syllabus.coursesyllabus')),
            ],
            options={
                'verbose_name': 'Student assessment',
                'verbose_name_plural': 'Student assessments',
            },
        ),
    ]
