# Generated by Django 3.2.1 on 2023-08-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_auto_20230825_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesyllabus',
            options={'verbose_name': 'Syllabus', 'verbose_name_plural': 'Syllabuses'},
        ),
    ]
