# Generated by Django 3.2.1 on 2023-08-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_alter_coursesyllabus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_syllabuses', to='syllabus.syllabus', verbose_name='Department Syllabus'),
        ),
    ]
