# Generated by Django 3.2.1 on 2023-08-25 19:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_alter_coursesyllabus_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabustextsection',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='if you choose 5_assessment_methods type, you can use table_procedure_assessment key for procedure assessment table', null=True, verbose_name='Text'),
        ),
    ]
