# Generated by Django 3.2.1 on 2023-08-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0013_alter_coursesyllabustextsection_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesyllabustest',
            options={'verbose_name': 'Syllabus test', 'verbose_name_plural': 'Syllabus tests'},
        ),
    ]
