# Generated by Django 3.2.1 on 2023-09-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0140_delete_externalimage'),
        ('syllabus', '0014_alter_coursesyllabustest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabus',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_syllabuses', to='admin_panel.direction'),
            preserve_default=False,
        ),
    ]
