# Generated by Django 3.2.1 on 2023-09-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0015_coursesyllabus_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonResourceLecture',
            fields=[
            ],
            options={
                'verbose_name': 'Course lesson lecture',
                'verbose_name_plural': 'Course lesson lectures',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('syllabus.courselessonresource',),
        ),
        migrations.AlterField(
            model_name='courselessonresource',
            name='type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('video', 'Video'), ('file', 'File'), ('url', 'URL')], max_length=255, verbose_name='Type'),
        ),
    ]
