# Generated by Django 3.2.1 on 2023-09-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0016_auto_20230904_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonResourceSingleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('file', models.FileField(blank=True, null=True, upload_to='course_lesson_resource_files', verbose_name='File')),
                ('course_lesson_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson_resource_single_files', to='syllabus.courselessonresource', verbose_name='Course lesson resource')),
            ],
            options={
                'verbose_name': 'Course lesson resource single file',
                'verbose_name_plural': 'Course lesson resource single files',
            },
        ),
    ]
