# Generated by Django 3.2.1 on 2023-09-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0017_courselessonresourcesinglefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselessonresourcesinglefile',
            name='course_lesson_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='syllabus.courselessonresource', verbose_name='Course lesson resource'),
        ),
    ]
