# Generated by Django 3.2.1 on 2023-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0018_alter_courselessonresourcesinglefile_course_lesson_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabus',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesyllabustest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
