# Generated by Django 3.2.1 on 2024-05-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0019_auto_20230915_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselessonhour',
            name='type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('laboratory', 'Laboratory'), ('practice', 'Practice'), ('exam', 'Exam'), ('independent_education', 'Independent Education')], max_length=255, verbose_name='Type'),
        ),
    ]
