# Generated by Django 3.2.1 on 2024-05-14 12:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0020_alter_courselessonhour_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesyllabustest',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesyllabustest',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesyllabustest',
            name='title_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='coursesyllabustest',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_sr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Question'),
        ),
    ]
